In [9]:
#MNIST데이터 손글씨 아라비아 숫자 0~9 데이터

#http://yann.lecun.com/exdb/mnist/ 에서 학습 데이터, 테스트 데이터 다운로드 가능

#데이터 input은 아래 스크립트 활용 https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials/mnist

import input_data

import numpy as np

import tensorflow as tf

mnist = input_data.read_data_sets("./mnist_data", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./mnist_data\train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting ./mnist_data\train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting ./mnist_data\t10k-images-idx3-ubyte.gz
Extracting ./mnist_data\t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [10]:
#100개 이미지 학습

train_pixels,train_list_values = mnist.train.next_batch(100)

#print(train_pixels)

#print(train_list_values)

#10개 테스트

test_pixels,test_list_of_values = mnist.test.next_batch(10)

print(test_list_of_values)

[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [11]:
#텐서 정의

train_pixel_tensor = tf.placeholder("float",[None,784])

test_pixel_tensor = tf.placeholder("float",[784])

In [12]:
#비용함수 정의 텐서의 차원을 탐색하며 개체들의 총합 계산   _reduce_sum 함수: 텐서의 차원을 탐색하며 개체의 총합 계산

distance = tf.reduce_sum(tf.abs(tf.add(train_pixel_tensor,tf.negative(test_pixel_tensor))),reduction_indices=1)



#reduce_sum

#x=[[1,1,1],[1,1,1]]

#tf.reduce_sum(x) -> 6

#tf.reduce_sum(x,0) -> [2,2,2]

#tf.reduce_sum(x,1) -> [3,3]

#tf.reduce_sum(x,1,keep_dims=True) -> [[3],[3]]

#tf.reduce_sum(x,[0,1]) -> 6

In [13]:
#비용함수 최소화를 위해 arg_min 사용 가장 작은 거리를 갖는 인덱스 리턴(최근접 이웃)

pred = tf.arg_min(distance,0)

Instructions for updating:
Use `tf.math.argmin` instead


In [18]:
accuracy=0

init = tf.global_variables_initializer()

with tf.Session() as sess:

    sess.run(init)

    for i in range(len(test_list_of_values)):

        nn_index = sess.run(pred, feed_dict={train_pixel_tensor:train_pixels, test_pixel_tensor:test_pixels[i,:]})

        print("Test No. ",i,"Predict Class: ",np.argmax(train_list_values[nn_index]),"True class: ",np.argmax(test_list_of_values[i]))

        if np.argmax(train_list_values[nn_index])==np.argmax(test_list_of_values[i]):

            accuracy+=1.0/len(test_pixels)

    print("Result Accuracy =",accuracy)

Test No.  0 Predict Class:  3 True class:  8
Test No.  1 Predict Class:  2 True class:  2
Test No.  2 Predict Class:  4 True class:  4
Test No.  3 Predict Class:  4 True class:  7
Test No.  4 Predict Class:  3 True class:  3
Test No.  5 Predict Class:  1 True class:  8
Test No.  6 Predict Class:  4 True class:  9
Test No.  7 Predict Class:  4 True class:  4
Test No.  8 Predict Class:  4 True class:  4
Test No.  9 Predict Class:  6 True class:  6
Result Accuracy = 0.6
